version: "3.9"

services:
  db:
    image: postgis/postgis:16-3.5
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgis
      POSTGRES_USER: postgis
      POSTGRES_PASSWORD: postgis
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgis"]
      interval: 2s
      timeout: 2s
      retries: 10
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      APPLICATION_POSTGRES_HOST: db
    ports:
      - "8000:8000"

volumes:
  db_data:
